pipeline {
    agent none

    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:latest' }
            }
            steps {
                sh 'mvn --version'
                sh 'echo "removing maven container....."'
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:latest' }
            }
            steps {
                sh 'node --version'
                sh 'echo "removing node container....."'
            }
        }
        stage('Database') {
            agent {
                docker { image 'your-database-image:tag' }
            }
            steps {
                sh 'echo "Running database commands..."'
                sh 'echo "removing sql container....."'
            }
        }
    }
}
