pipeline {
    agent none

    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                sh 'mvn --version'
                sh 'echo "removing maven container....."'
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'node --version'
                sh 'echo "removing node container....."'
            }
        }
        stage('Database') {
            agent {
                docker { image 'mysql:latest' }
            }
            steps {
                sh 'mysql --version'
                sh 'echo "removing sql container....."'
            }
        }
    }
}
